### ISSUE TITLE
volume go back to 100% temperately after resume from sleep 

### ISSUE THREAD

**Issue by NOirBRight** [valadaa48/retroroller#134]
no matter what volume level you set.
If you go to sleep and resume, the volume will go back to 100% for about 1 second then set to you previous level.
both in archlinux and rrvl.

**Comment by valadaa48** [comment]
do you know if this happens in other images?

**Comment by valadaa48** [comment]
The reason I ask is because I thought joy fixed this issue in the kernel. I fixed this in rrvl. Please test and if it works then I'll apply to RR.

**Comment by NOirBRight** [comment]
no, the volume issue is still there.
this issue was also in rr2.0 early build, but fixed later.

**Comment by NOirBRight** [comment]
![image](https://user-images.githubusercontent.com/271412/86097189-e37bb080-bae6-11ea-9954-3ca0299a4394.png)
it fixed in rr2.0 after I pointed it.

**Comment by NOirBRight** [comment]
the volume will be 100% after resume for about 1 second then go back to what you set in RRVL.

**Comment by NOirBRight** [comment]
1.0.3_2 seems fixed this.
