### ISSUE TITLE
RRVL RA 1.9.0_17 glcore driver issue

### ISSUE THREAD

**Issue by raidenii** [valadaa48/retroroller#188]
Hello,

RA 1.9.0_17 has issue for glcore drivers for flycast and ppsspp core on OGA. Namely, games failed to start under RA 1.9.0_17 with video driver set to "glcore" and core option "Allow cores to switch the video driver" set to "false". In retroarch.log the following message was printed:

```
[INFO] [Environ]: GET_PREFERRED_HW_RENDER.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGLES2 context.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGLES2 context.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGLES2 context.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGLES2 context.
[ERROR] [CONTENT LOAD]: Failed to load content
```

flycast core at commit e3b8bc9 and ppsspp core at commit 6ca01d5. Downgrading retroarch to 1.9.0_16 and both cores work fine with video driver = glcore and Allow cores to switch the video driver = false.

**Comment by valadaa48** [comment]
Thanks for the info. My guess is that we picked up a regression in retroarch along the way. What I will try to do is apply the retroarch work I did to the old _16 version and hopefully this issue goes away.

> flycast core at commit e3b8bc9 and ppsspp core at commit 6ca01d5. 
which commits are you referring to? Are these cores downloaded from our core updater?

**Comment by raidenii** [comment]
commit of their own repo. For ppsspp it's from RRVL repo, the flycast core I compiled myself.

**Comment by valadaa48** [comment]
I git bisected and indeed someone broke this in September. https://github.com/libretro/RetroArch/issues/11487

I'll see if I can revert that commit if it helps.

**Comment by valadaa48** [comment]
I pushed out a new retroarch with that commit reverted. Can you try it out and close the issue if all good?

**Comment by raidenii** [comment]
Unfortunately, with version 18 of RA it still failed to work.

**Comment by valadaa48** [comment]
oops, hold on a sec.. forgot to sync out 20

**Comment by valadaa48** [comment]
OK it's out there

**Comment by raidenii** [comment]
Thanks, it works fine now.

**Comment by raidenii** [comment]
Looks like it needs cores with the new code choosing renderers. Mind providing them on your repo?
