### ISSUE TITLE
emuelec-emulationstation "Missing Bios" Menu option reports "No Missing Bios"

### ISSUE THREAD

**Issue by shoesio** [valadaa48/retroroller#64]
Games Settings / Missing Bios /
I havn't added any, so I'm guessing there are missing bios really.

**Comment by valadaa48** [comment]
fixed in latest version

**Comment by shoesio** [comment]
Just tested this - issue still present v: emuelec-emulationstation-3520.d7800b31-1

**Comment by adventureFAN** [comment]
Can confirm that with the latest version

**Comment by shoesio** [comment]
Think this has been closed in error. Still experiencing this issue here.
